### ISSUE TITLE
Implement missing features to avoid false positive

### ISSUE THREAD

**Issue by alexdupre** [scalacenter/sbt-missinglink#12]
Given that most scala projects depends on at least logback and/or slf4j it'd be very useful to implement the following feature to avoid false positives:

- Excluding some dependencies from the analysis
- Ignoring conflicts in certain packages

**Comment by danslapman** [comment]
There're 3 (three) PR's already...

**Comment by sjrd** [comment]
Fixed in 6682d601d70f00e516272d6726e6e054a07c96d1 and 14f07bd635c088ca84e525af1fcc9c38f5ab9d98.
