### ISSUE TITLE
CME in build with multiple projects

### ISSUE THREAD

**Issue by OlegYch** [scalacenter/sbt-missinglink#26]
missinglink is not thread-safe so it fails or produces inconsistent results if you have run it on more than one project.
Please see https://github.com/OlegYch/sbt-missinglink/commit/f0e0c09b37a9b65ded44fa71b4c2c1ffa73dc754 for a fix.

**Comment by sjrd** [comment]
Hi @OlegYch! Thank you for the report and for pointing out a fix, which seems reasonable to me. Would you like to send a PR with just that?

Btw, what does CME stand for?
